# Generated by Django 3.2.5 on 2021-07-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя')),
                ('username', models.TextField(verbose_name='Логин пользователя')),
                ('firstname', models.TextField(verbose_name='Имя пользователя')),
                ('lastname', models.TextField(verbose_name='Фамилия пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время первого запуска')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
